import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable{
    // -1 means from client to server, otherwise it is generated by the server
    private Integer ID;
    private long timestamp; // same rule
    private long TTL = 2000; // 2 seconds
    private long realDate;
    private Object data;
    private Username username;

    public Message(Integer ID, long timestamp, Object data, Username username) {
        this.ID = ID;
        this.timestamp = timestamp;
        this.data = data;
        this.realDate = (new Date()).getTime();
        this.username = username;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public long getTimestamp() {
        return this.timestamp;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public Integer getID() {
        return this.ID;
    }

    public Object getData() {
        return this.data;
    }

    public void setTTL(long TTL) {
        this.TTL = TTL;
    }

    public long getTTL() {
        return this.TTL;
    }

    public long getRealDate() {
        return this.realDate;
    }

    public Username getUsername() {
        return this.username;
    }
}
