
import java.io.Serializable;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * container for any type of object to be sent
 * @author dosse
 */
public class Message implements Serializable{
    private Integer chId; //-1 means from client to server, otherwise chId generated by the server
    private long timestamp, //-1 means from client to server, otherwise timeStamp of the moment when the server receives the message
            ttl=2000; //2 seconds TTL
    private Object data; //can carry any type of object. in this program, i used a sound packet, but it could be a string, a chunk of video, ...

    
    public Message(Integer chId, long timestamp, Object data) {
        this.chId = chId;
        this.timestamp = timestamp;
        this.data = data;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public Integer getID() {
        return chId;
    }

    public Object getData() {
        return data;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public long getTtl() {
        return ttl;
    }
    public void setTtl(long ttl) {
        this.ttl = ttl;
    }
    
    public void setID(Integer chId) {
        this.chId = chId;
    }

}
